"""add employee onboarding tables and hr role

Revision ID: b7b2b788e585
Revises: 33a60cdb2dae
Create Date: 2026-09-15 09:47:59.687043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7b2b788e585'
down_revision: Union[str, Sequence[str], None] = '33a60cdb2dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Autogenerate also picked up unrelated constraint/index drift
    # (categories_name_key, uq_users_email, uq_users_entra_object_id) that
    # predates this change and isn't part of it - trimmed out, same as the
    # two migrations before this one.
    #
    # Adding a value to an EXISTING Postgres enum type (roleenum already has
    # admin/technician/requester) needs ALTER TYPE ... ADD VALUE, which
    # Postgres refuses to run inside the same transaction as anything that
    # might use the new value - and (on older Postgres, <12) refuses inside
    # any transaction block at all. autocommit_block() runs this statement
    # on its own, outside Alembic's normal per-migration transaction, same
    # spirit as the explicit enum-type .create() call needed for a brand
    # new enum column (see 33a60cdb2dae).
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE roleenum ADD VALUE IF NOT EXISTS 'hr'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_job_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('default_workstation_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_job_titles_id'), 'onboarding_job_titles', ['id'], unique=False)
    op.create_index(op.f('ix_onboarding_job_titles_title'), 'onboarding_job_titles', ['title'], unique=True)
    op.create_table('onboarding_notification_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('recipient_name', sa.String(), nullable=True),
    sa.Column('recipient_email', sa.String(), nullable=True),
    sa.Column('cc', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_notification_recipients_id'), 'onboarding_notification_recipients', ['id'], unique=False)
    op.create_index(op.f('ix_onboarding_notification_recipients_trigger'), 'onboarding_notification_recipients', ['trigger'], unique=False)
    op.create_table('onboarding_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'in_progress', 'completed', 'cancelled', name='onboardingbatchstatus'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('master_ticket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['master_ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_batches_id'), 'onboarding_batches', ['id'], unique=False)
    op.create_table('onboarding_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('clinic_site_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('is_rehire', sa.Boolean(), nullable=False),
    sa.Column('workstation_type', sa.String(), nullable=True),
    sa.Column('requires_dexis', sa.Boolean(), nullable=True),
    sa.Column('requires_fastattach', sa.Boolean(), nullable=True),
    sa.Column('workstation_suite', sa.String(), nullable=True),
    sa.Column('assigned_email', sa.String(), nullable=True),
    sa.Column('stage', sa.Enum('it_identity', 'ehr_provisioning', 'clinical_training', 'ready', name='onboardingstage'), nullable=False),
    sa.Column('child_ticket_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['onboarding_batches.id'], ),
    sa.ForeignKeyConstraint(['child_ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['clinic_site_id'], ['clinic_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_candidates_id'), 'onboarding_candidates', ['id'], unique=False)
    op.create_table('onboarding_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('task_name', sa.String(), nullable=True),
    sa.Column('assigned_role', sa.Enum('it_infrastructure', 'ehr_admin', 'clinical_trainer', 'dental_trainer', name='onboardingassignedrole'), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('depends_on_task_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', name='onboardingtaskstatus'), nullable=False),
    sa.Column('completed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('triggers_stage1_handoff', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['onboarding_candidates.id'], ),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['onboarding_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_tasks_id'), 'onboarding_tasks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Postgres has no ALTER TYPE ... DROP VALUE at all - removing 'hr' from
    # roleenum would mean rebuilding the type and every column using it. Not
    # worth the risk/complexity for a downgrade path; any 'hr' users would
    # need to be reassigned a role manually first anyway. Leaving 'hr' in
    # the enum on downgrade is a deliberate, documented limitation.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarding_tasks_id'), table_name='onboarding_tasks')
    op.drop_table('onboarding_tasks')
    op.drop_index(op.f('ix_onboarding_candidates_id'), table_name='onboarding_candidates')
    op.drop_table('onboarding_candidates')
    op.drop_index(op.f('ix_onboarding_batches_id'), table_name='onboarding_batches')
    op.drop_table('onboarding_batches')
    op.drop_index(op.f('ix_onboarding_notification_recipients_trigger'), table_name='onboarding_notification_recipients')
    op.drop_index(op.f('ix_onboarding_notification_recipients_id'), table_name='onboarding_notification_recipients')
    op.drop_table('onboarding_notification_recipients')
    op.drop_index(op.f('ix_onboarding_job_titles_title'), table_name='onboarding_job_titles')
    op.drop_index(op.f('ix_onboarding_job_titles_id'), table_name='onboarding_job_titles')
    op.drop_table('onboarding_job_titles')
    # ### end Alembic commands ###

    # op.drop_table() does NOT drop the Postgres ENUM types the dropped
    # columns used (confirmed the hard way - a downgrade then re-upgrade
    # failed with "type onboardingbatchstatus already exists", since the
    # type silently survived the table drop). Same explicit-cleanup
    # requirement as CREATE TYPE needing an explicit .create() call on the
    # way up (see 33a60cdb2dae) - here it's .drop() on the way down.
    for type_name in ("onboardingassignedrole", "onboardingtaskstatus", "onboardingstage", "onboardingbatchstatus"):
        sa.Enum(name=type_name).drop(op.get_bind(), checkfirst=True)
